package domain

import (
	"crypto/rand"
	"time"
)

// InviteCodeLength is the length of generated invite codes.
const InviteCodeLength = 8

// inviteAlphabet is uppercase alphanumerics minus the visually confusable
// characters 0, O, 1, I, and L, so codes are unambiguous to hand-type. A User
// joins a Team by typing the code its Team Owner shared with them.
const inviteAlphabet = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"

// InviteCode is a single-use, revocable credential that lets a User join a
// Team as a Member. It is generated by a Team Owner, consumed on first use,
// and revoked by deleting the row while it is still unused.
type InviteCode struct {
	ID        int64      `json:"id" gorm:"primaryKey"`
	TeamID    int64      `json:"team_id" gorm:"index"`
	Code      string     `json:"code" gorm:"uniqueIndex;size:32"`
	CreatedBy int64      `json:"created_by"`
	CreatedAt time.Time  `json:"created_at"`
	UsedBy    *int64     `json:"used_by"`
	UsedAt    *time.Time `json:"used_at"`
}

// GenerateInviteCode returns a random code from the unambiguous alphabet.
func GenerateInviteCode() (string, error) {
	b := make([]byte, InviteCodeLength)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	for i := range b {
		b[i] = inviteAlphabet[int(b[i])%len(inviteAlphabet)]
	}
	return string(b), nil
}
